### ISSUE TITLE
Computing Curvatures in Fiji

### ISSUE THREAD

**Issue by kmader** [Quantitative-Big-Imaging/Quantitative-Big-Imaging-Course#4]
I have a question regarding the curvature computation with Fiji. In the exercises 6, we had to draw some shapes (circle, ellipses) and we had to run curvature computation.

To simplify, I draw only one circle. And I expected to get only one image in which to each pixel on the surface of the circle would be assigned a value of 1/R +- some errors due to gradient estimation by blurring the image with Gaussian. When I think about the surface of the circle I mean the curve x^2 + y^2 = R^2. Here is a link which confirms that for a circle, I should get curvature kapa = 1/R (equation 30). 

I was surprised that I get two images and I don't know how to interpret them.  Are those ellipsis interpreted in some way as 3D objects by Fiji? 

Could you try to explain me what is Fiji's output from curvature computation for a single circle.

**Comment by kmader** [comment]
The values for curvature calculated with the “Calculate Curvature” plugin in Fiji do not agree with the mathematical definition of 1/R. This is due to the nature of the computation, rather than being computed from the surface it is being computed from a Gaussian filtered (smoothed) binary image. The sigma for the filter affects the strength of the blurring and since the result is derived from the Hessian the “curvature”. The “curvature” is thus a relative metric which can with a fairly tedious derivation be related back to mathematical curvature. For most practical purposes, this is sufficient for comparing the curvature of different structures. Attached you can see the curvature calculations for the same image using a weak (sigma=4, top row) and a strong (sigma=8, bottom row) filtering. When comparing the peak values (the others can be ignored and usually are by excluding points not on the surface), the ratio between the small and large circle remain the same although the absolute values change by a factor of 2. 
![image](https://cloud.githubusercontent.com/assets/116120/3738268/d9766320-173e-11e4-9094-c0614485869f.png)

**Comment by jmmccra2** [comment]
I have 3 semi-complex b&w line drawings and I want to extract relative curvature values from them.  I have tried applying the Computing Curvatures plug-in in Fiji, and found that a weak sigma=4 produced potentially interesting image results, which I can quantify easily in MATLAB.

However, as in one of the previous comments on this plug-in:

"I was surprised that I get two images and I don't know how to interpret them."

Where do I go to find further documentation on the interpretation of the results of this plug-in?
